"""Late Game Blowout Strategy - I_Strategy implementation.

Activates in the last 10 minutes of a game when one team has a commanding lead.
This is a low-risk strategy since teams rarely come back from large deficits late.

Entry criteria:
- Q4 (or OT) with <= 10 minutes remaining
- Score differential >= threshold (default 12 points)
- Buy YES on the leading team

Risk profile: Very low - historical comeback rates from 10+ down with <10 min are ~5%

Ported from src/strategies/late_game_blowout.py to implement I_Strategy interface.
"""

import asyncio
import logging
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from .i_strategy import I_Strategy
from .strategy_types import Signal, StrategyConfig
from core.order_manager import I_OrderManager, Side
from core.exchange_client import I_ExchangeClient
from core.market import I_Market

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Original domain types from src/strategies/late_game_blowout.py
# ---------------------------------------------------------------------------


class BlowoutSide(Enum):
    """Which team is leading (original Side enum, renamed to avoid clash with core.order_manager.Side)."""

    HOME = "home"
    AWAY = "away"


@dataclass
class BlowoutSignal:
    """Signal generated by late game blowout strategy."""

    timestamp: float
    game_id: str
    leading_team: BlowoutSide
    score_differential: int  # Always positive (leader's advantage)
    home_score: int
    away_score: int
    period: int
    time_remaining_seconds: int
    win_probability: float  # Estimated P(leader wins)
    confidence: str  # 'medium', 'high', 'very_high'

    @property
    def trailing_team(self) -> BlowoutSide:
        return (
            BlowoutSide.AWAY
            if self.leading_team == BlowoutSide.HOME
            else BlowoutSide.HOME
        )


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass
class LateGameBlowoutConfig(StrategyConfig):
    """Configuration for late game blowout strategy.

    Mirrors BlowoutStrategyConfig from the original module with
    from_yaml_dict / to_yaml_dict for YAML template loading.
    """

    # Entry thresholds
    min_point_differential: int = 12  # Minimum lead required (12+ is safer)
    max_time_remaining_seconds: int = 600  # 10 minutes
    min_period: int = 4  # Q4 or later (OT)

    # Confidence tiers based on lead size
    high_confidence_threshold: int = 15  # 15+ point lead
    very_high_confidence_threshold: int = 20  # 20+ point lead

    # Position sizing by confidence
    base_position_size: float = 5.0  # $5 base bet
    high_confidence_multiplier: float = 1.5  # $7.50 for high confidence
    very_high_confidence_multiplier: float = 2.0  # $10 for very high confidence

    # Price limits - don't buy if price is too high (already priced in)
    max_buy_price: float = 0.92  # Don't buy above 92 cents
    min_edge_required: float = 0.02  # Require 2% edge minimum

    # Stop loss settings
    stop_loss_threshold: int = 5  # Exit if lead drops to 5 or below
    stop_loss_min_time_remaining: int = 180  # Only trigger if > 3 min left

    # Timing
    tick_interval_seconds: float = 5.0  # How often to check markets

    # Market filter
    nba_market_prefix: str = "KXNBAGAME"  # Ticker prefix for NBA game markets

    @classmethod
    def from_yaml_dict(cls, data: Dict[str, Any]) -> "LateGameBlowoutConfig":
        """Create LateGameBlowoutConfig from parsed YAML dict."""
        entry = data.get("entry", {})
        confidence = data.get("confidence", {})
        position = data.get("position", {})
        price = data.get("price", {})
        stop_loss = data.get("stop_loss", {})
        timing = data.get("timing", {})
        filters = data.get("filters", {})

        return cls(
            min_point_differential=entry.get("min_point_differential", 12),
            max_time_remaining_seconds=entry.get("max_time_remaining_seconds", 600),
            min_period=entry.get("min_period", 4),
            high_confidence_threshold=confidence.get("high_threshold", 15),
            very_high_confidence_threshold=confidence.get("very_high_threshold", 20),
            base_position_size=position.get("base_size", 5.0),
            high_confidence_multiplier=position.get("high_multiplier", 1.5),
            very_high_confidence_multiplier=position.get("very_high_multiplier", 2.0),
            max_buy_price=price.get("max_buy_price", 0.92),
            min_edge_required=price.get("min_edge_required", 0.02),
            stop_loss_threshold=stop_loss.get("threshold", 5),
            stop_loss_min_time_remaining=stop_loss.get("min_time_remaining", 180),
            tick_interval_seconds=timing.get("tick_interval_seconds", 5.0),
            nba_market_prefix=filters.get("nba_market_prefix", "KXNBAGAME"),
        )

    def to_yaml_dict(self) -> Dict[str, Any]:
        """Convert to YAML-serializable dict."""
        return {
            "strategy": "LateGameBlowoutStrategy",
            "version": 1,
            "entry": {
                "min_point_differential": self.min_point_differential,
                "max_time_remaining_seconds": self.max_time_remaining_seconds,
                "min_period": self.min_period,
            },
            "confidence": {
                "high_threshold": self.high_confidence_threshold,
                "very_high_threshold": self.very_high_confidence_threshold,
            },
            "position": {
                "base_size": self.base_position_size,
                "high_multiplier": self.high_confidence_multiplier,
                "very_high_multiplier": self.very_high_confidence_multiplier,
            },
            "price": {
                "max_buy_price": self.max_buy_price,
                "min_edge_required": self.min_edge_required,
            },
            "stop_loss": {
                "threshold": self.stop_loss_threshold,
                "min_time_remaining": self.stop_loss_min_time_remaining,
            },
            "timing": {
                "tick_interval_seconds": self.tick_interval_seconds,
            },
            "filters": {
                "nba_market_prefix": self.nba_market_prefix,
            },
        }


# ---------------------------------------------------------------------------
# Helper functions (ported verbatim from src/strategies/late_game_blowout.py)
# ---------------------------------------------------------------------------


def calculate_stop_loss_from_stats(
    win_rate: float,
    avg_win: float,
    avg_contracts: float = 5,
    avg_entry_price: float = 0.90,
    avg_entry_fee: float = 0.0,
    avg_exit_fee: float = 0.0,
    safety_margin: float = 0.7,
) -> Dict:
    """
    Calculate optimal price stop loss from historical win rate and P&L.

    The breakeven condition for a strategy is:
        win_rate * avg_win = (1 - win_rate) * max_loss_per_trade

    Solving for max_loss gives the largest stop loss that keeps the strategy
    profitable. A safety margin is applied to create a buffer.

    The dollar loss on a stopped trade is:
        loss = (stop_cents / 100) * contracts + entry_fee + exit_fee

    So we invert that to get stop_cents from the dollar amount.
    Cents are capped at entry_price (can't lose more than you paid).

    Args:
        win_rate: Historical win rate (0.0 to 1.0)
        avg_win: Average profit per winning trade (dollars, after fees)
        avg_contracts: Average contracts per trade (for cents conversion)
        avg_entry_price: Average entry price (for capping cents at max possible loss)
        avg_entry_fee: Average entry fee per trade (dollars)
        avg_exit_fee: Average exit fee on stopped trades (dollars)
        safety_margin: Fraction of breakeven to use (default 0.7 = 30% buffer)

    Returns:
        Dict with breakeven and recommended stop loss in dollars and cents
    """
    if win_rate <= 0 or win_rate >= 1 or avg_win <= 0:
        return {
            "error": "Need win_rate in (0,1) and avg_win > 0",
            "win_rate": win_rate,
            "avg_win": avg_win,
        }

    # Max loss per trade at breakeven
    breakeven_loss = (win_rate / (1 - win_rate)) * avg_win

    # Cap at max possible loss (lose entire position + entry fee)
    max_possible_loss = avg_entry_price * avg_contracts + avg_entry_fee
    breakeven_capped = breakeven_loss > max_possible_loss

    # Apply safety margin
    recommended_loss = breakeven_loss * safety_margin

    # Convert to cents below entry price
    # loss = (stop_cents/100) * contracts + entry_fee + exit_fee
    # stop_cents = (loss - entry_fee - exit_fee) / contracts * 100
    # Cap at entry_price in cents (can't drop below $0)
    max_cents = avg_entry_price * 100
    avg_fees = avg_entry_fee + avg_exit_fee
    if avg_contracts > 0:
        breakeven_cents = min(
            max_cents, max(0, (breakeven_loss - avg_fees) / avg_contracts * 100)
        )
        recommended_cents = min(
            max_cents, max(0, (recommended_loss - avg_fees) / avg_contracts * 100)
        )
    else:
        breakeven_cents = 0
        recommended_cents = 0

    return {
        "win_rate": win_rate,
        "avg_win": avg_win,
        "breakeven_loss_dollars": round(min(breakeven_loss, max_possible_loss), 2),
        "recommended_loss_dollars": round(min(recommended_loss, max_possible_loss), 2),
        "breakeven_cents": round(breakeven_cents, 1),
        "recommended_cents": round(recommended_cents, 1),
        "breakeven_capped": breakeven_capped,
        "safety_margin": safety_margin,
        "avg_contracts": avg_contracts,
        "avg_entry_price": avg_entry_price,
        "avg_fees_per_trade": round(avg_fees, 2),
    }


def backtest_blowout_strategy(
    game_snapshots: List[Dict],
    config: Optional[LateGameBlowoutConfig] = None,
) -> Dict:
    """
    Backtest the blowout strategy on recorded game data.

    Args:
        game_snapshots: List of game state snapshots with keys:
            - timestamp, home_score, away_score, period, time_remaining
            - home_price, away_price (optional)
            - game_result: 'home' or 'away' (who won)
        config: Strategy configuration

    Returns:
        Dict with backtest results
    """
    strategy = LateGameBlowoutStrategy(config=config)

    trades = []
    pnl = 0.0
    wins = 0
    losses = 0

    # Track if we've already traded this game
    traded_games: set = set()

    for snap in game_snapshots:
        game_id = snap.get("game_id", "unknown")

        # Skip if already traded this game
        if game_id in traded_games:
            continue

        blowout_signal = strategy._check_entry(
            home_score=snap["home_score"],
            away_score=snap["away_score"],
            period=snap["period"],
            time_remaining=snap["time_remaining"],
            timestamp=snap["timestamp"],
            game_id=game_id,
            home_price=snap.get("home_price"),
            away_price=snap.get("away_price"),
        )

        if blowout_signal:
            traded_games.add(game_id)

            # Determine if trade won
            game_result = snap.get("game_result")
            if game_result:
                position_size = strategy._get_position_size(blowout_signal.confidence)

                # Get the price we bought at
                if blowout_signal.leading_team == BlowoutSide.HOME:
                    buy_price = snap.get("home_price", 0.90)
                else:
                    buy_price = snap.get("away_price", 0.90)

                # Did we win?
                if (
                    blowout_signal.leading_team == BlowoutSide.HOME
                    and game_result == "home"
                ) or (
                    blowout_signal.leading_team == BlowoutSide.AWAY
                    and game_result == "away"
                ):
                    # Won - profit is (1 - buy_price) * position_size
                    trade_pnl = (1.0 - buy_price) * position_size
                    wins += 1
                else:
                    # Lost - lose entire position
                    trade_pnl = -buy_price * position_size
                    losses += 1

                pnl += trade_pnl

                trades.append(
                    {
                        "timestamp": snap["timestamp"],
                        "game_id": game_id,
                        "leading_team": blowout_signal.leading_team.value,
                        "score_diff": blowout_signal.score_differential,
                        "time_remaining": blowout_signal.time_remaining_seconds,
                        "confidence": blowout_signal.confidence,
                        "buy_price": buy_price,
                        "position_size": position_size,
                        "result": "win" if trade_pnl > 0 else "loss",
                        "pnl": trade_pnl,
                    }
                )

    total_trades = wins + losses
    win_rate = wins / total_trades if total_trades > 0 else 0

    return {
        "total_trades": total_trades,
        "wins": wins,
        "losses": losses,
        "win_rate": win_rate,
        "total_pnl": pnl,
        "avg_pnl_per_trade": pnl / total_trades if total_trades > 0 else 0,
        "trades": trades,
    }


# ---------------------------------------------------------------------------
# Strategy (I_Strategy implementation)
# ---------------------------------------------------------------------------


class LateGameBlowoutStrategy(I_Strategy):
    """Late game blowout strategy implementing I_Strategy.

    Buys the leading team when they have a commanding lead late in the game.
    Wraps all original business logic from src/strategies/late_game_blowout.py.

    Example:
        >>> from core import KalshiExchangeClient, KalshiOrderManager
        >>> client = KalshiExchangeClient.from_env()
        >>> om = KalshiOrderManager(client)
        >>> strategy = LateGameBlowoutStrategy(
        ...     exchange_client=client, order_manager=om,
        ...     tickers=["KXNBAGAME-...YES", "KXNBAGAME-...NO"],
        ... )
        >>> await strategy.run()
    """

    def __init__(
        self,
        exchange_client: Optional[I_ExchangeClient] = None,
        order_manager: Optional[I_OrderManager] = None,
        tickers: Optional[List[str]] = None,
        config: Optional[LateGameBlowoutConfig] = None,
        dry_run: bool = True,
    ):
        self._client = exchange_client
        self._om = order_manager
        self._tickers = tickers or []
        self._config = config or LateGameBlowoutConfig()
        self._dry_run = dry_run

        self._markets: Dict[str, I_Market] = {}
        self._selected_markets: List[I_Market] = []
        self._running = False
        self._logs: List[str] = []
        self._signals_generated: List[BlowoutSignal] = []

    # ------------------------------------------------------------------
    # Original helper methods (ported from LateGameBlowoutStrategy in
    # src/strategies/late_game_blowout.py)
    # ------------------------------------------------------------------

    @staticmethod
    def parse_time_remaining(time_str: str) -> int:
        """Parse NBA time string to seconds."""
        try:
            # Remove any quarter info (e.g., "Q4 4:21" -> "4:21")
            time_str = time_str.split()[-1]

            parts = time_str.split(":")
            if len(parts) == 2:
                minutes = int(parts[0])
                seconds = float(parts[1])
                return int(minutes * 60 + seconds)
            elif len(parts) == 1:
                return int(float(parts[0]))
        except Exception:
            pass
        return 0

    def calculate_win_probability(
        self,
        score_diff: int,
        time_remaining_seconds: int,
    ) -> float:
        """
        Calculate win probability for leading team in late game.

        Uses empirical NBA data:
        - Teams leading by 10+ with <10 min left win ~95% of the time
        - Each additional point adds ~1% to win probability
        - Each minute less remaining adds ~0.5% to win probability
        """
        # Base probability for 10-point lead with 10 minutes left
        base_prob = 0.95

        # Adjust for point differential beyond 10
        point_bonus = (score_diff - 10) * 0.01

        # Adjust for time remaining (less time = more certain)
        # 10 min = 0 bonus, 5 min = 2.5% bonus, 2 min = 4% bonus
        time_bonus = (600 - time_remaining_seconds) / 600 * 0.05

        win_prob = base_prob + point_bonus + time_bonus

        # Clip to reasonable range
        return min(0.99, max(0.90, win_prob))

    def _get_confidence_tier(self, score_diff: int) -> str:
        """Determine confidence tier based on lead size."""
        if score_diff >= self._config.very_high_confidence_threshold:
            return "very_high"
        elif score_diff >= self._config.high_confidence_threshold:
            return "high"
        else:
            return "medium"

    def _get_position_size(self, confidence: str) -> float:
        """Get position size based on confidence tier."""
        if confidence == "very_high":
            return (
                self._config.base_position_size
                * self._config.very_high_confidence_multiplier
            )
        elif confidence == "high":
            return (
                self._config.base_position_size
                * self._config.high_confidence_multiplier
            )
        else:
            return self._config.base_position_size

    def check_stop_loss(
        self,
        current_lead: int,
        time_remaining: str,
        entry_lead: int,
    ) -> bool:
        """
        Check if stop loss should be triggered.

        Args:
            current_lead: Current point differential (positive = our team leading)
            time_remaining: Time remaining string
            entry_lead: Lead when we entered the trade

        Returns:
            True if we should exit (stop loss triggered), False otherwise

        Stop loss logic:
        - If lead shrinks to stop_loss_threshold (default 5) or below
        - AND there's more than stop_loss_min_time_remaining (default 3 min) left
        - Then exit to avoid a full loss

        Rationale: Early lead shrinkage = real danger of comeback
                   Late shrinkage (< 3 min) = normal variance, ride it out
        """
        time_remaining_seconds = self.parse_time_remaining(time_remaining)

        # Only trigger stop loss if there's still significant time left
        if time_remaining_seconds <= self._config.stop_loss_min_time_remaining:
            return False  # Too late to stop loss, just ride it out

        # Check if lead has shrunk to danger zone
        if current_lead <= self._config.stop_loss_threshold:
            return True

        return False

    def get_stop_loss_info(self) -> dict:
        """Get stop loss configuration info."""
        return {
            "threshold": self._config.stop_loss_threshold,
            "min_time_remaining": self._config.stop_loss_min_time_remaining,
            "description": (
                f"Exit if lead drops to +{self._config.stop_loss_threshold} or below "
                f"with >{self._config.stop_loss_min_time_remaining // 60} min remaining"
            ),
        }

    def _check_entry(
        self,
        home_score: int,
        away_score: int,
        period: int,
        time_remaining: str,
        timestamp: float,
        game_id: str = "",
        home_price: Optional[float] = None,
        away_price: Optional[float] = None,
    ) -> Optional[BlowoutSignal]:
        """
        Check if entry conditions are met.

        Args:
            home_score: Current home team score
            away_score: Current away team score
            period: Current period (4 = Q4, 5+ = OT)
            time_remaining: Time remaining string (e.g., "8:30")
            timestamp: Current timestamp
            game_id: Game identifier
            home_price: Current price for home team YES (optional, for edge calc)
            away_price: Current price for away team YES (optional, for edge calc)

        Returns:
            BlowoutSignal if conditions met, None otherwise
        """
        # Check period - must be Q4 or later
        if period < self._config.min_period:
            return None

        # Parse time remaining
        time_remaining_seconds = self.parse_time_remaining(time_remaining)

        # Check time - must be in last 10 minutes
        if time_remaining_seconds > self._config.max_time_remaining_seconds:
            return None

        # Calculate score differential
        score_diff = abs(home_score - away_score)

        # Check if lead is large enough
        if score_diff < self._config.min_point_differential:
            return None

        # Determine leading team
        if home_score > away_score:
            leading_team = BlowoutSide.HOME
            leader_price = home_price
        else:
            leading_team = BlowoutSide.AWAY
            leader_price = away_price

        # Calculate win probability
        win_prob = self.calculate_win_probability(score_diff, time_remaining_seconds)

        # Check price if available - ensure we have edge
        if leader_price is not None:
            if leader_price > self._config.max_buy_price:
                return None  # Price too high, not worth it

            edge = win_prob - leader_price
            if edge < self._config.min_edge_required:
                return None  # Not enough edge

        # Get confidence tier
        confidence = self._get_confidence_tier(score_diff)

        # Generate signal
        signal = BlowoutSignal(
            timestamp=timestamp,
            game_id=game_id,
            leading_team=leading_team,
            score_differential=score_diff,
            home_score=home_score,
            away_score=away_score,
            period=period,
            time_remaining_seconds=time_remaining_seconds,
            win_probability=win_prob,
            confidence=confidence,
        )

        self._signals_generated.append(signal)
        return signal

    def get_trade_recommendation(
        self,
        signal: BlowoutSignal,
        home_ticker: str,
        away_ticker: str,
    ) -> Dict:
        """
        Get trade recommendation from signal.

        Returns:
            Dict with ticker, side, size, and rationale
        """
        position_size = self._get_position_size(signal.confidence)

        if signal.leading_team == BlowoutSide.HOME:
            ticker = home_ticker
            team_desc = "home"
        else:
            ticker = away_ticker
            team_desc = "away"

        return {
            "action": "BUY",
            "side": "YES",
            "ticker": ticker,
            "size": position_size,
            "confidence": signal.confidence,
            "rationale": (
                f"Late game blowout: {team_desc} team leads by {signal.score_differential} "
                f"with {signal.time_remaining_seconds // 60}:{signal.time_remaining_seconds % 60:02d} remaining. "
                f"Win probability: {signal.win_probability:.1%}"
            ),
            "win_probability": signal.win_probability,
            "score_differential": signal.score_differential,
            "time_remaining_seconds": signal.time_remaining_seconds,
        }

    # ------------------------------------------------------------------
    # Conversion: BlowoutSignal -> MrClean Signal
    # ------------------------------------------------------------------

    @staticmethod
    def _blowout_signal_to_signal(blowout_signal: Optional[BlowoutSignal]) -> Signal:
        """Convert a BlowoutSignal to the MrClean Signal type.

        Maps:
        - BlowoutSide.HOME / AWAY -> Side.YES (we always buy YES on the leading team's market)
        - confidence 'medium' / 'high' / 'very_high' -> strength 0.4 / 0.7 / 1.0
        - win_probability -> target_price_cents (cents, e.g. 0.95 -> 95)
        """
        if blowout_signal is None:
            return Signal.no_signal("No blowout entry conditions met")

        # Map confidence string to numeric strength
        confidence_to_strength = {
            "medium": 0.4,
            "high": 0.7,
            "very_high": 1.0,
        }
        strength = confidence_to_strength.get(blowout_signal.confidence, 0.4)

        # Target price is the win probability expressed in cents
        target_price_cents = int(round(blowout_signal.win_probability * 100))

        reason = (
            f"Late game blowout: "
            f"{'home' if blowout_signal.leading_team == BlowoutSide.HOME else 'away'} "
            f"leads by {blowout_signal.score_differential} "
            f"with {blowout_signal.time_remaining_seconds // 60}:"
            f"{blowout_signal.time_remaining_seconds % 60:02d} remaining "
            f"(P(win)={blowout_signal.win_probability:.1%}, "
            f"confidence={blowout_signal.confidence})"
        )

        return Signal.buy(
            side=Side.YES,
            price_cents=target_price_cents,
            strength=strength,
            reason=reason,
        )

    # ------------------------------------------------------------------
    # I_Strategy interface implementation
    # ------------------------------------------------------------------

    def market_filter(self, market: Any) -> bool:
        """Filter for NBA game markets.

        Checks that the market ticker starts with the configured NBA
        prefix (default ``KXNBAGAME``).
        """
        ticker = ""
        if hasattr(market, "ticker"):
            ticker = market.ticker
        elif isinstance(market, dict):
            ticker = market.get("ticker", "")
        elif isinstance(market, str):
            ticker = market

        return ticker.startswith(self._config.nba_market_prefix)

    def get_candidate_markets(self) -> List[Any]:
        """Return all loaded markets that pass the NBA filter."""
        return [m for m in self._markets.values() if self.market_filter(m)]

    def get_selected_markets(self) -> List[Any]:
        """Return markets currently selected for trading."""
        return self._selected_markets

    def select_markets(self, markets: List[Any]) -> None:
        """Select markets to actively trade."""
        self._selected_markets = markets
        self.log(f"Selected {len(markets)} markets for trading")

    def get_signal(self, market: Any) -> Signal:
        """Get trading signal for a market.

        Extracts game state from the market object, runs ``_check_entry``
        to produce a ``BlowoutSignal``, and converts it to a MrClean ``Signal``.
        """
        # Extract game state from market
        game_state = self._extract_game_state(market)
        if game_state is None:
            return Signal.no_signal("Unable to extract game state from market")

        blowout_signal = self._check_entry(**game_state)
        return self._blowout_signal_to_signal(blowout_signal)

    async def load_markets(self) -> None:
        """Load initial market data for all tickers."""
        if self._client is None:
            self.log("No exchange client configured, skipping market load")
            return

        from core.market import KalshiMarket
        from core.exchange_client import KalshiMarketData

        for ticker in self._tickers:
            try:
                market_data: KalshiMarketData = await self._client.request_market(
                    ticker
                )
                self._markets[ticker] = KalshiMarket(market_data, self._client)
                self.log(f"Loaded market: {ticker}")
            except Exception as e:
                self.log(f"Failed to load {ticker}: {e}")

    async def refresh_markets(self) -> None:
        """Refresh market data for selected markets."""
        for market in self._selected_markets:
            try:
                await market.update_orderbook()
            except Exception as e:
                self.log(f"Failed to update {market.ticker}: {e}")

    async def on_tick(self) -> None:
        """Called on each tick/update cycle.

        Refreshes market data, then evaluates ``get_signal`` for every
        selected market and logs actionable signals.
        """
        await self.refresh_markets()

        for market in self._selected_markets:
            signal = self.get_signal(market)
            if signal.has_signal:
                self.log(
                    f"SIGNAL [{signal.strength_level.value}]: "
                    f"{market.ticker} - {signal.reason}"
                )

    async def run(self) -> None:
        """Main strategy loop."""
        if self._client is not None and not self._client.is_connected:
            await self._client.connect()

        self._running = True
        self.log(
            f"Starting LateGameBlowoutStrategy on {len(self._tickers)} markets "
            f"(dry_run={self._dry_run})"
        )

        # CRITICAL: Initialize OMS (cancel stale orders, recover positions)
        if self._om:
            try:
                await self._om.initialize()
                self.log("OMS initialized: stale orders cancelled, positions recovered")
            except Exception as e:
                logger.error(f"OMS initialization failed: {e}")
                # Continue anyway - OMS will track positions from new fills

        # Initial market load
        await self.load_markets()

        # Select markets
        candidates = self.get_candidate_markets()
        self.select_markets(candidates)

        try:
            while self._running:
                await self.on_tick()
                await asyncio.sleep(self._config.tick_interval_seconds)
        except asyncio.CancelledError:
            self.log("Strategy cancelled")
        finally:
            self._running = False
            self.log("Strategy stopped")

    def stop(self) -> None:
        """Stop the strategy loop."""
        self._running = False

    def log(self, message: str) -> None:
        """Log strategy activity."""
        ts = datetime.now().strftime("%H:%M:%S")
        log_msg = f"[{ts}] LateGameBlowoutStrategy: {message}"
        self._logs.append(log_msg)
        logger.info(message)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _extract_game_state(self, market: Any) -> Optional[Dict]:
        """Extract game state dict from a market object for _check_entry.

        Supports I_Market objects with a ``game_state`` attribute or dict,
        and plain dicts (e.g. from a data feed / backtest).
        """
        import time as _time

        # If market is already a dict with the right keys, use directly
        if isinstance(market, dict):
            required = {"home_score", "away_score", "period", "time_remaining"}
            if required.issubset(market.keys()):
                return {
                    "home_score": market["home_score"],
                    "away_score": market["away_score"],
                    "period": market["period"],
                    "time_remaining": market["time_remaining"],
                    "timestamp": market.get("timestamp", _time.time()),
                    "game_id": market.get("game_id", ""),
                    "home_price": market.get("home_price"),
                    "away_price": market.get("away_price"),
                }
            return None

        # I_Market with game_state attribute (e.g. from live feed)
        if hasattr(market, "game_state"):
            gs = market.game_state
            if gs is None:
                return None
            # game_state may be a dict or a dataclass-like object
            if isinstance(gs, dict):
                return self._extract_game_state(gs)
            return {
                "home_score": getattr(gs, "home_score", 0),
                "away_score": getattr(gs, "away_score", 0),
                "period": getattr(gs, "period", 0),
                "time_remaining": getattr(gs, "time_remaining", "0:00"),
                "timestamp": getattr(gs, "timestamp", _time.time()),
                "game_id": getattr(gs, "game_id", getattr(market, "ticker", "")),
                "home_price": getattr(gs, "home_price", None),
                "away_price": getattr(gs, "away_price", None),
            }

        # Try to extract from orderbook prices as a fallback
        # (only price info, no scoreboard -- not enough for this strategy)
        return None

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def signals_generated(self) -> List[BlowoutSignal]:
        """All BlowoutSignals generated during this session."""
        return list(self._signals_generated)

    @property
    def is_running(self) -> bool:
        """Whether the strategy is actively running."""
        return self._running

    @property
    def config(self) -> LateGameBlowoutConfig:
        """Current strategy configuration."""
        return self._config

    def get_logs(self, n: int = 50) -> List[str]:
        """Get recent log entries."""
        return self._logs[-n:]


# Backward compat alias
BlowoutStrategyConfig = LateGameBlowoutConfig
