"""
Tied Game Narrow Margin Strategy

Exploits mispricing of narrow margin spread contracts when teams are tied during NBA games.

Hypothesis: When teams are tied, markets overestimate the probability of narrow finishes
(2-3 point margins), making "NO" contracts underpriced.

Edge: Buy NO on narrow margin contracts when tied, capturing the difference between
market-implied and theoretical probabilities.

Theoretical Foundation (using normal distribution model from ScoreAnalyzer):
- Final margin ~ N(current_diff, sigma) where sigma = 10 * sqrt(2 * time_remaining_fraction)
- When tied (diff=0), P(win by 2-3 pts) = Phi(3.5/sigma) - Phi(1.5/sigma)

| Game State     | sigma | P(one team wins by 2-3) | P(NOT 2-3) |
|----------------|-------|-------------------------|------------|
| Q1 tied        | 13.2  | 5.9%                    | 94.1%      |
| Halftime tied  | 10.0  | 7.7%                    | 92.3%      |
| Q3 end tied    | 7.1   | 10.6%                   | 89.4%      |
| Q4 5min tied   | 4.6   | 15.0%                   | 85.0%      |

If market prices narrow margin YES at 12% when theoretical is 7.7%, NO is underpriced by ~4 cents.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional
import numpy as np
from scipy.stats import norm


@dataclass
class TiedGameSpreadConfig:
    """Configuration for tied game narrow margin strategy."""

    max_score_differential: int = 2  # Trade when tied or within 2 pts
    min_edge_cents: float = 2.0  # Minimum edge to trade
    max_period: int = 3  # Don't trade Q4 (variance too compressed)
    position_size: int = 10  # Contracts per trade
    target_margin_low: float = 1.5  # Win by 2+ (> 1.5)
    target_margin_high: float = 3.5  # Win by up to 3 (< 3.5)
    cooldown_seconds: float = 60.0  # Cooldown between signals for same team


@dataclass
class TiedGameSpreadSignal:
    """Signal generated by tied game spread strategy."""

    timestamp: float
    game_id: str
    period: int
    time_remaining_seconds: int
    score_differential: int  # home - away
    theoretical_narrow_prob: float  # From normal model
    market_narrow_prob: float  # From spread prices
    edge_cents: float
    direction: str  # "BUY_NO"
    team: str  # "home" or "away" - which team's spread contract
    ticker: str  # The spread ticker to trade

    # Market data used for calculation
    p_over_low: float  # P(margin > 1.5)
    p_over_high: float  # P(margin > 3.5)

    @property
    def theoretical_no_prob(self) -> float:
        """Probability that margin will NOT be in narrow range (2-3 pts)."""
        return 1.0 - self.theoretical_narrow_prob

    @property
    def market_no_prob(self) -> float:
        """Market-implied probability of NOT narrow margin."""
        return 1.0 - self.market_narrow_prob


class TiedGameSpreadStrategy:
    """
    Tied Game Narrow Margin Strategy.

    When teams are tied (or close), this strategy identifies mispricings in
    narrow margin spread contracts by comparing theoretical probabilities
    (from normal distribution model) to market-implied probabilities.

    The strategy buys NO on narrow margin contracts when the market overestimates
    the probability of a 2-3 point margin finish.

    Example usage:
        config = TiedGameSpreadConfig(min_edge_cents=2.0, max_period=3)
        strategy = TiedGameSpreadStrategy(config)

        signal = strategy.check_entry(
            score=game_score,
            home_spreads={"1": {"bid": 0.45, "ask": 0.48}, "4": {"bid": 0.35, "ask": 0.38}},
            away_spreads={"1": {"bid": 0.42, "ask": 0.45}, "4": {"bid": 0.33, "ask": 0.36}},
            home_spread_ticker="KXNBASPREAD-HOME-1",
            away_spread_ticker="KXNBASPREAD-AWAY-1",
        )

        if signal:
            print(f"Signal: {signal.direction} on {signal.team} @ {signal.edge_cents}c edge")
    """

    # Total regulation time in NBA: 48 minutes = 2880 seconds
    TOTAL_REGULATION_TIME = 2880
    QUARTER_LENGTH = 720  # 12 minutes per quarter
    OT_LENGTH = 300  # 5 minutes per OT

    # Empirical standard deviation for NBA scoring (points per team)
    SIGMA_PER_TEAM = 10.0

    def __init__(self, config: Optional[TiedGameSpreadConfig] = None):
        """Initialize the strategy.

        Args:
            config: Strategy configuration. Uses defaults if not provided.
        """
        self.config = config or TiedGameSpreadConfig()
        self.signals_generated: List[TiedGameSpreadSignal] = []
        self._last_signal_time: Dict[str, float] = {}  # team -> timestamp

    def calculate_sigma(self, time_remaining_fraction: float) -> float:
        """Calculate standard deviation of final margin.

        Uses the CLT model: sigma_diff = 10 * sqrt(2 * time_remaining_fraction)

        Args:
            time_remaining_fraction: Fraction of game remaining (0 to 1)

        Returns:
            Standard deviation of expected final margin
        """
        return self.SIGMA_PER_TEAM * np.sqrt(2.0 * time_remaining_fraction)

    def calculate_time_remaining_fraction(
        self, period: int, time_remaining_seconds: int
    ) -> float:
        """Calculate what fraction of the game remains.

        Args:
            period: Current period (1-4 regulation, 5+ OT)
            time_remaining_seconds: Seconds remaining in current period

        Returns:
            Fraction of game remaining (0 to 1)
        """
        if period <= 4:
            # Regulation
            time_elapsed = (period - 1) * self.QUARTER_LENGTH + (
                self.QUARTER_LENGTH - time_remaining_seconds
            )
            return max(
                0.001,
                (self.TOTAL_REGULATION_TIME - time_elapsed)
                / self.TOTAL_REGULATION_TIME,
            )
        else:
            # Overtime - treat as additional time beyond regulation
            ot_period = period - 4
            total_time = self.TOTAL_REGULATION_TIME + ot_period * self.OT_LENGTH
            time_elapsed = (
                self.TOTAL_REGULATION_TIME
                + (ot_period - 1) * self.OT_LENGTH
                + (self.OT_LENGTH - time_remaining_seconds)
            )
            return max(0.001, (total_time - time_elapsed) / total_time)

    def calculate_theoretical_prob(
        self, score_diff: int, period: int, time_remaining_seconds: int
    ) -> float:
        """Calculate theoretical probability of narrow margin (2-3 pts) finish.

        Uses normal distribution model:
        - Final margin ~ N(current_diff, sigma)
        - P(narrow) = P(1.5 < |margin| <= 3.5)

        For tied games (diff=0), this simplifies to:
        - P(narrow) = 2 * [Phi(3.5/sigma) - Phi(1.5/sigma)]

        Args:
            score_diff: Current score differential (home - away)
            period: Current period
            time_remaining_seconds: Seconds remaining in current period

        Returns:
            Probability of narrow margin finish (2-3 points either way)
        """
        time_frac = self.calculate_time_remaining_fraction(
            period, time_remaining_seconds
        )
        sigma = self.calculate_sigma(time_frac)

        # Avoid division by zero
        if sigma < 0.1:
            return 0.0

        # For a narrow margin win (by 2-3 points), we need:
        # P(team wins by 2-3) = P(1.5 < margin <= 3.5) where margin is from that team's perspective

        # Home wins by 2-3: P(1.5 < final_margin <= 3.5)
        # where final_margin ~ N(score_diff, sigma)
        home_narrow = norm.cdf((3.5 - score_diff) / sigma) - norm.cdf(
            (1.5 - score_diff) / sigma
        )

        # Away wins by 2-3: P(-3.5 <= final_margin < -1.5)
        away_narrow = norm.cdf((-1.5 - score_diff) / sigma) - norm.cdf(
            (-3.5 - score_diff) / sigma
        )

        # Total probability of any narrow margin finish
        return home_narrow + away_narrow

    def calculate_market_implied_prob(
        self, p_over_low: float, p_over_high: float
    ) -> float:
        """Calculate market-implied probability of narrow margin from spread prices.

        P(win by 2-3) = P(margin > 1.5) - P(margin > 3.5)

        Args:
            p_over_low: Market probability of margin > 1.5 (from spread "1" contract)
            p_over_high: Market probability of margin > 3.5 (from spread "4" contract)

        Returns:
            Market-implied probability of narrow margin (2-3 pts)
        """
        # P(exactly 2-3 point margin) = P(>1.5) - P(>3.5)
        return max(0.0, p_over_low - p_over_high)

    def _parse_time_remaining(self, time_str: str) -> int:
        """Parse NBA time string to seconds.

        Args:
            time_str: Time string like "4:30" or "Q4 4:30"

        Returns:
            Time remaining in seconds
        """
        try:
            # Remove any quarter info
            time_str = time_str.split()[-1]

            parts = time_str.split(":")
            if len(parts) == 2:
                minutes = int(parts[0])
                seconds = float(parts[1])
                return int(minutes * 60 + seconds)
            elif len(parts) == 1:
                return int(float(parts[0]))
        except (ValueError, IndexError):
            pass
        return 0

    def _can_signal(self, team: str, timestamp: float) -> bool:
        """Check if we can generate a signal for this team (cooldown check).

        Args:
            team: "home" or "away"
            timestamp: Current timestamp

        Returns:
            True if cooldown has elapsed, False otherwise
        """
        last_time = self._last_signal_time.get(team, 0.0)
        return (timestamp - last_time) >= self.config.cooldown_seconds

    def check_entry(
        self,
        home_score: int,
        away_score: int,
        period: int,
        time_remaining: str,
        timestamp: float,
        game_id: str,
        home_spreads: Dict[str, Dict[str, float]],
        away_spreads: Dict[str, Dict[str, float]],
        home_spread_ticker: str = "",
        away_spread_ticker: str = "",
    ) -> Optional[TiedGameSpreadSignal]:
        """Check if entry conditions are met for a narrow margin spread trade.

        Args:
            home_score: Current home team score
            away_score: Current away team score
            period: Current period (1-4 regulation, 5+ OT)
            time_remaining: Time remaining string (e.g., "4:30")
            timestamp: Current timestamp
            game_id: Game identifier
            home_spreads: Home team spread data by threshold
                         {"1": {"bid": 0.45, "ask": 0.48}, "4": {"bid": 0.35, "ask": 0.38}}
            away_spreads: Away team spread data by threshold (same format)
            home_spread_ticker: Ticker for home team's narrow margin spread contract
            away_spread_ticker: Ticker for away team's narrow margin spread contract

        Returns:
            TiedGameSpreadSignal if conditions met, None otherwise
        """
        # 1. Check if tied or close
        score_diff = home_score - away_score
        if abs(score_diff) > self.config.max_score_differential:
            return None

        # 2. Check period (skip Q4 - variance too compressed, model less reliable)
        if period > self.config.max_period:
            return None

        # 3. Parse and validate time
        time_remaining_seconds = self._parse_time_remaining(time_remaining)

        # 4. Calculate theoretical P(narrow margin) for this game state
        time_frac = self.calculate_time_remaining_fraction(
            period, time_remaining_seconds
        )
        self.calculate_sigma(time_frac)
        theoretical_narrow_prob = self.calculate_theoretical_prob(
            score_diff, period, time_remaining_seconds
        )

        # 5. Check each team's spread contracts for edge
        best_signal: Optional[TiedGameSpreadSignal] = None
        best_edge = 0.0

        for team, spreads, ticker in [
            ("home", home_spreads, home_spread_ticker),
            ("away", away_spreads, away_spread_ticker),
        ]:
            # Check cooldown
            if not self._can_signal(team, timestamp):
                continue

            # Get spread prices (need "1" for >1.5 and "4" for >3.5)
            if "1" not in spreads or "4" not in spreads:
                continue

            spread_1 = spreads["1"]
            spread_4 = spreads["4"]

            # Calculate mid prices
            p_over_1_5 = (spread_1["bid"] + spread_1["ask"]) / 2
            p_over_3_5 = (spread_4["bid"] + spread_4["ask"]) / 2

            # Calculate market-implied narrow probability for this team
            market_narrow_prob = self.calculate_market_implied_prob(
                p_over_1_5, p_over_3_5
            )

            # For a single team's narrow margin, theoretical is half the total
            # (since theoretical_narrow_prob includes both teams)
            # But market prices are for one specific team, so compare directly
            # Actually: market prices for "home wins by 2-3" should be compared
            # to theoretical P(home wins by 2-3)
            team_theoretical = theoretical_narrow_prob / 2.0

            # Calculate edge on NO side
            # If market prices YES at market_narrow_prob, then NO is priced at (1 - market_narrow_prob)
            # Theoretical NO probability is (1 - team_theoretical)
            # Edge = theoretical_no - market_no = (1 - team_theoretical) - (1 - market_narrow_prob)
            #      = market_narrow_prob - team_theoretical
            edge = market_narrow_prob - team_theoretical
            edge_cents = edge * 100

            if edge_cents >= self.config.min_edge_cents and edge_cents > best_edge:
                best_edge = edge_cents
                best_signal = TiedGameSpreadSignal(
                    timestamp=timestamp,
                    game_id=game_id,
                    period=period,
                    time_remaining_seconds=time_remaining_seconds,
                    score_differential=score_diff,
                    theoretical_narrow_prob=team_theoretical,
                    market_narrow_prob=market_narrow_prob,
                    edge_cents=edge_cents,
                    direction="BUY_NO",
                    team=team,
                    ticker=ticker,
                    p_over_low=p_over_1_5,
                    p_over_high=p_over_3_5,
                )

        if best_signal:
            self._last_signal_time[best_signal.team] = timestamp
            self.signals_generated.append(best_signal)

        return best_signal

    def get_trade_recommendation(self, signal: TiedGameSpreadSignal) -> Dict:
        """Get trade recommendation from a signal.

        Args:
            signal: Signal to convert to trade recommendation

        Returns:
            Dict with trade details
        """
        return {
            "action": "BUY",
            "side": "NO",
            "ticker": signal.ticker,
            "size": self.config.position_size,
            "edge_cents": signal.edge_cents,
            "rationale": (
                f"Tied game narrow margin: {signal.team} spread | "
                f"Market implies {signal.market_narrow_prob:.1%} narrow finish, "
                f"theoretical is {signal.theoretical_narrow_prob:.1%} | "
                f"Edge: {signal.edge_cents:.1f}c on NO"
            ),
            "theoretical_prob": signal.theoretical_no_prob,
            "market_prob": signal.market_no_prob,
            "period": signal.period,
            "time_remaining_seconds": signal.time_remaining_seconds,
            "score_differential": signal.score_differential,
        }

    def reset(self) -> None:
        """Reset strategy state (for backtesting multiple games)."""
        self.signals_generated = []
        self._last_signal_time = {}
