"""
NBA Total Points Over/Under Strategy

Calculates P(final_total > line) at any point in the game and compares it to
Kalshi total points market prices to find edge.

Mathematical Model:
    Final_total ~ N(current_total + expected_remaining, sigma_total)

Where:
    - expected_remaining = blended_pace * time_remaining_minutes
    - blended_pace = weighted average of current game pace and NBA average
    - sigma_total = volatility * sqrt(time_remaining_fraction)

P(total > line) = 1 - Phi((line - projected_total) / sigma)

Key Features:
    - Pace blending: Weights current game pace more heavily as game progresses
    - Second half boost: NBA games typically score more in the second half
    - Slow game regression: Extra boost when first half scoring is unusually low
"""

import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
from scipy.stats import norm


@dataclass
class TotalPointsConfig:
    """Configuration for total points over/under strategy.

    Default values optimized via parameter sweep on 13 NBA game recordings.
    Achieved Mean RMSE of 9.85 points with these settings.
    """

    # Trading parameters
    min_edge_cents: float = 3.0  # Minimum edge to trade
    position_size: int = 10  # Contracts per trade
    max_period: int = 3  # Trade Q1-Q3 (not late Q4)
    cooldown_seconds: float = 60.0  # Cooldown between signals

    # Model parameters (tunable via backtesting)
    nba_avg_pace: float = 4.6  # Combined pts/min (roughly 2.3 * 2 teams)
    sigma_per_team: float = 10.0  # Std dev per team for scoring variance

    # Pace blending (tunable)
    # Optimized: moderate blending (0.5) outperforms high blending
    pace_blend_start: float = 0.2  # Weight on current pace at game start
    pace_blend_end: float = 0.5  # Weight on current pace late game
    min_time_for_pace: float = 0.1  # Min game % before using current pace

    # Second half boost (tunable)
    # Optimized: no boost (0.0) gives best RMSE
    enable_second_half_boost: bool = False
    second_half_boost: float = 0.0  # Expected 2H scoring boost in points

    # Slow game regression (tunable)
    # Optimized: 10 point boost for slow games
    enable_slow_game_boost: bool = True
    slow_game_threshold: float = 103.0  # Halftime total below this = slow game
    slow_game_extra_boost: float = 10.0  # Extra boost for slow games


@dataclass
class TotalPointsSignal:
    """Signal generated by total points over/under strategy."""

    timestamp: float
    game_id: str
    ticker: str
    line: float  # e.g., 223.5
    current_total: int
    time_remaining_fraction: float
    projected_total: float  # Our model's projection
    theoretical_over_prob: float  # P(total > line)
    market_over_prob: float  # From Kalshi price
    edge_cents: float
    direction: str  # "BUY_OVER" or "BUY_UNDER"

    # Debug info for tuning
    blended_pace: float
    boost_applied: float
    sigma: float
    period: int
    time_remaining_str: str

    @property
    def theoretical_under_prob(self) -> float:
        """P(total <= line)."""
        return 1.0 - self.theoretical_over_prob

    @property
    def market_under_prob(self) -> float:
        """Market-implied P(total <= line)."""
        return 1.0 - self.market_over_prob


class TotalPointsStrategy:
    """
    NBA Total Points Over/Under Strategy.

    Identifies mispricings in total points markets by comparing theoretical
    probabilities (from a pace-based projection model) to market-implied
    probabilities from Kalshi prices.

    Example usage:
        config = TotalPointsConfig(min_edge_cents=3.0, max_period=3)
        strategy = TotalPointsStrategy(config)

        signal = strategy.check_entry(
            home_score=52,
            away_score=48,
            period=2,
            time_remaining="6:30",
            timestamp=1234567890.0,
            game_id="0022500001",
            line=223.5,
            market_over_bid=0.52,
            market_over_ask=0.54,
            ticker="KXNBATOTAL-26JAN22LALLAC-223",
        )

        if signal:
            print(f"Signal: {signal.direction} @ {signal.edge_cents:.1f}c edge")
    """

    # Total regulation time in NBA: 48 minutes = 2880 seconds
    TOTAL_REGULATION_TIME = 2880
    QUARTER_LENGTH = 720  # 12 minutes per quarter
    OT_LENGTH = 300  # 5 minutes per OT

    def __init__(self, config: Optional[TotalPointsConfig] = None):
        """Initialize the strategy.

        Args:
            config: Strategy configuration. Uses defaults if not provided.
        """
        self.config = config or TotalPointsConfig()
        self.signals_generated: List[TotalPointsSignal] = []
        self._last_signal_time: float = 0.0
        self._halftime_total: Optional[int] = None

    def calculate_time_remaining_fraction(
        self, period: int, time_remaining_seconds: int
    ) -> float:
        """Calculate what fraction of the game remains.

        Args:
            period: Current period (1-4 regulation, 5+ OT)
            time_remaining_seconds: Seconds remaining in current period

        Returns:
            Fraction of game remaining (0 to 1)
        """
        if period <= 4:
            # Regulation
            time_elapsed = (period - 1) * self.QUARTER_LENGTH + (
                self.QUARTER_LENGTH - time_remaining_seconds
            )
            return max(
                0.001,
                (self.TOTAL_REGULATION_TIME - time_elapsed)
                / self.TOTAL_REGULATION_TIME,
            )
        else:
            # Overtime - treat as additional time beyond regulation
            ot_period = period - 4
            total_time = self.TOTAL_REGULATION_TIME + ot_period * self.OT_LENGTH
            time_elapsed = (
                self.TOTAL_REGULATION_TIME
                + (ot_period - 1) * self.OT_LENGTH
                + (self.OT_LENGTH - time_remaining_seconds)
            )
            return max(0.001, (total_time - time_elapsed) / total_time)

    def calculate_pace_weight(self, game_completion_frac: float) -> float:
        """Calculate how much to weight current game pace vs NBA average.

        Weight increases linearly as game progresses (more data = more reliable).

        Args:
            game_completion_frac: Fraction of game completed (0 to 1)

        Returns:
            Weight to apply to current game pace (0 to pace_blend_end)
        """
        if game_completion_frac < self.config.min_time_for_pace:
            return 0.0  # Too early, use only NBA average

        # Linear interpolation from start to end weight
        progress = min(1.0, game_completion_frac)
        return (
            self.config.pace_blend_start
            + (self.config.pace_blend_end - self.config.pace_blend_start) * progress
        )

    def calculate_blended_pace(
        self, current_total: int, game_completion_frac: float
    ) -> float:
        """Blend current game pace with NBA average.

        Args:
            current_total: Current combined score
            game_completion_frac: Fraction of game completed

        Returns:
            Blended pace in points per minute
        """
        if game_completion_frac < self.config.min_time_for_pace:
            return self.config.nba_avg_pace

        elapsed_minutes = game_completion_frac * 48
        if elapsed_minutes > 0:
            current_pace = current_total / elapsed_minutes
        else:
            current_pace = self.config.nba_avg_pace

        weight = self.calculate_pace_weight(game_completion_frac)
        return (1 - weight) * self.config.nba_avg_pace + weight * current_pace

    def calculate_projected_total(
        self,
        current_total: int,
        time_remaining_frac: float,
        halftime_total: Optional[int] = None,
    ) -> Tuple[float, float, float]:
        """Project final total score with tunable adjustments.

        Args:
            current_total: Current combined score
            time_remaining_frac: Fraction of game remaining
            halftime_total: Total score at halftime (if known)

        Returns:
            Tuple of (projected_total, blended_pace, boost_applied)
        """
        game_completion = 1.0 - time_remaining_frac
        remaining_minutes = time_remaining_frac * 48

        # Blended pace projection
        blended_pace = self.calculate_blended_pace(current_total, game_completion)
        expected_remaining = blended_pace * remaining_minutes

        # Second half boost (if enabled and we're in first half)
        boost = 0.0
        if self.config.enable_second_half_boost and time_remaining_frac > 0.5:
            # Scale boost by how much of second half remains
            # Full boost at halftime, zero boost at end of game
            second_half_frac = (time_remaining_frac - 0.5) / 0.5
            boost = self.config.second_half_boost * second_half_frac

        # Slow game regression boost (if enabled and at/past halftime)
        if halftime_total is not None:
            if (
                self.config.enable_slow_game_boost
                and halftime_total < self.config.slow_game_threshold
            ):
                boost += self.config.slow_game_extra_boost

        projected = current_total + expected_remaining + boost
        return projected, blended_pace, boost

    def calculate_sigma(self, time_remaining_frac: float) -> float:
        """Calculate standard deviation of final total.

        Combined variance = 2 * per-team variance
        Scales with sqrt of remaining time.

        Args:
            time_remaining_frac: Fraction of game remaining

        Returns:
            Standard deviation of projected total
        """
        # sigma_total = sigma_per_team * sqrt(2 * time_remaining)
        return self.config.sigma_per_team * np.sqrt(2 * time_remaining_frac)

    def calculate_over_probability(
        self,
        current_total: int,
        line: float,
        period: int,
        time_remaining_seconds: int,
        halftime_total: Optional[int] = None,
    ) -> Tuple[float, float, float, float]:
        """Calculate P(final_total > line).

        Args:
            current_total: Current combined score
            line: Points line to compare against
            period: Current period
            time_remaining_seconds: Seconds left in current period
            halftime_total: Total at halftime (if known)

        Returns:
            Tuple of (over_prob, projected_total, blended_pace, boost)
        """
        time_frac = self.calculate_time_remaining_fraction(
            period, time_remaining_seconds
        )
        projected, pace, boost = self.calculate_projected_total(
            current_total, time_frac, halftime_total
        )
        sigma = self.calculate_sigma(time_frac)

        # Avoid division by zero
        if sigma < 0.1:
            # Game essentially over, just compare current + minimal remaining
            return (1.0 if current_total > line else 0.0), projected, pace, boost

        # P(total > line) = 1 - Phi((line - projected) / sigma)
        z = (line - projected) / sigma
        over_prob = 1 - norm.cdf(z)

        return over_prob, projected, pace, boost

    def _parse_time_remaining(self, time_str: str) -> int:
        """Parse NBA time string to seconds.

        Args:
            time_str: Time string like "4:30" or "Q4 4:30"

        Returns:
            Time remaining in seconds
        """
        try:
            # Remove any quarter info
            time_str = time_str.split()[-1]

            parts = time_str.split(":")
            if len(parts) == 2:
                minutes = int(parts[0])
                seconds = float(parts[1])
                return int(minutes * 60 + seconds)
            elif len(parts) == 1:
                return int(float(parts[0]))
        except (ValueError, IndexError):
            pass
        return 0

    def _can_signal(self, timestamp: float) -> bool:
        """Check if cooldown has elapsed since last signal.

        Args:
            timestamp: Current timestamp

        Returns:
            True if cooldown has elapsed
        """
        return (timestamp - self._last_signal_time) >= self.config.cooldown_seconds

    def set_halftime_total(self, total: int) -> None:
        """Record halftime total for slow game boost calculations.

        Args:
            total: Combined score at halftime
        """
        self._halftime_total = total

    def check_entry(
        self,
        home_score: int,
        away_score: int,
        period: int,
        time_remaining: str,
        timestamp: float,
        game_id: str,
        line: float,
        market_over_bid: float,
        market_over_ask: float,
        ticker: str,
    ) -> Optional[TotalPointsSignal]:
        """Check if entry conditions are met for a total points trade.

        Args:
            home_score: Current home team score
            away_score: Current away team score
            period: Current period (1-4 regulation, 5+ OT)
            time_remaining: Time remaining string (e.g., "4:30")
            timestamp: Current timestamp
            game_id: Game identifier
            line: Total points line (e.g., 223.5)
            market_over_bid: Best bid for OVER contract (0-1)
            market_over_ask: Best ask for OVER contract (0-1)
            ticker: Market ticker for this total line

        Returns:
            TotalPointsSignal if conditions met, None otherwise
        """
        # 1. Check period (skip Q4 - model less reliable late game)
        if period > self.config.max_period:
            return None

        # 2. Check cooldown
        if not self._can_signal(timestamp):
            return None

        # 3. Parse time
        time_remaining_seconds = self._parse_time_remaining(time_remaining)
        time_frac = self.calculate_time_remaining_fraction(
            period, time_remaining_seconds
        )

        # 4. Calculate current total
        current_total = home_score + away_score

        # 5. Record halftime total if we're at halftime
        if period == 2 and time_remaining_seconds < 30:
            self._halftime_total = current_total

        # 6. Calculate theoretical probability
        over_prob, projected, pace, boost = self.calculate_over_probability(
            current_total, line, period, time_remaining_seconds, self._halftime_total
        )
        sigma = self.calculate_sigma(time_frac)

        # 7. Calculate market probability (midpoint of bid/ask)
        market_over_prob = (market_over_bid + market_over_ask) / 2

        # 8. Calculate edge
        over_edge = (over_prob - market_over_prob) * 100  # cents
        under_edge = (market_over_prob - over_prob) * 100  # cents (opposite direction)

        # 9. Check if edge is sufficient
        signal = None

        if over_edge >= self.config.min_edge_cents:
            signal = TotalPointsSignal(
                timestamp=timestamp,
                game_id=game_id,
                ticker=ticker,
                line=line,
                current_total=current_total,
                time_remaining_fraction=time_frac,
                projected_total=projected,
                theoretical_over_prob=over_prob,
                market_over_prob=market_over_prob,
                edge_cents=over_edge,
                direction="BUY_OVER",
                blended_pace=pace,
                boost_applied=boost,
                sigma=sigma,
                period=period,
                time_remaining_str=time_remaining,
            )
        elif under_edge >= self.config.min_edge_cents:
            signal = TotalPointsSignal(
                timestamp=timestamp,
                game_id=game_id,
                ticker=ticker,
                line=line,
                current_total=current_total,
                time_remaining_fraction=time_frac,
                projected_total=projected,
                theoretical_over_prob=over_prob,
                market_over_prob=market_over_prob,
                edge_cents=under_edge,
                direction="BUY_UNDER",
                blended_pace=pace,
                boost_applied=boost,
                sigma=sigma,
                period=period,
                time_remaining_str=time_remaining,
            )

        if signal:
            self._last_signal_time = timestamp
            self.signals_generated.append(signal)

        return signal

    def get_trade_recommendation(self, signal: TotalPointsSignal) -> Dict:
        """Get trade recommendation from a signal.

        Args:
            signal: Signal to convert to trade recommendation

        Returns:
            Dict with trade details
        """
        is_over = signal.direction == "BUY_OVER"
        return {
            "action": "BUY",
            "side": "YES" if is_over else "NO",
            "ticker": signal.ticker,
            "size": self.config.position_size,
            "edge_cents": signal.edge_cents,
            "rationale": (
                f"Total points {signal.direction}: Line {signal.line} | "
                f"Current {signal.current_total}, Projected {signal.projected_total:.1f} | "
                f"Theoretical P(over)={signal.theoretical_over_prob:.1%}, "
                f"Market={signal.market_over_prob:.1%} | "
                f"Edge: {signal.edge_cents:.1f}c"
            ),
            "theoretical_prob": signal.theoretical_over_prob
            if is_over
            else signal.theoretical_under_prob,
            "market_prob": signal.market_over_prob
            if is_over
            else signal.market_under_prob,
            "projected_total": signal.projected_total,
            "current_total": signal.current_total,
            "blended_pace": signal.blended_pace,
            "boost_applied": signal.boost_applied,
            "period": signal.period,
            "time_remaining": signal.time_remaining_str,
        }

    def reset(self) -> None:
        """Reset strategy state (for backtesting multiple games)."""
        self.signals_generated = []
        self._last_signal_time = 0.0
        self._halftime_total = None


def extract_line_from_ticker(ticker: str) -> Optional[float]:
    """Extract points line from ticker like KXNBATOTAL-26JAN22LALLAC-223.

    Args:
        ticker: Market ticker string

    Returns:
        Points line as float, or None if not found
    """
    # Try to match a number at the end of the ticker
    match = re.search(r"-(\d+(?:\.\d+)?)$", ticker)
    if match:
        return float(match.group(1))
    return None
