"""Abstract base class for trading strategies.

This module provides the foundation for implementing trading strategies that
integrate with the existing infrastructure (RiskManager, APIClient, paper trading).
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from src.core.interfaces import APIClient
from src.core.models import Fill, MarketState
from src.risk.risk_manager import RiskManager


@dataclass
class Signal:
    """A trading signal generated by a strategy.

    Attributes:
        ticker: Market identifier
        side: Order side ('BID' or 'ASK')
        price: Limit price (0-100 cents or 0.0-1.0 as probability)
        size: Number of contracts
        confidence: Signal confidence score (0-1)
        reason: Human-readable reason for the signal
        timestamp: When the signal was generated
        metadata: Additional signal-specific data
    """

    ticker: str
    side: str  # 'BID' or 'ASK'
    price: float
    size: int
    confidence: float
    reason: str
    timestamp: datetime
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate signal data."""
        if self.side not in ("BID", "ASK"):
            raise ValueError(f"Signal side must be 'BID' or 'ASK', got '{self.side}'")
        if not 0 <= self.confidence <= 1:
            raise ValueError(f"Signal confidence must be 0-1, got {self.confidence}")
        if self.size <= 0:
            raise ValueError(f"Signal size must be positive, got {self.size}")


@dataclass
class StrategyConfig:
    """Base configuration for strategies.

    Attributes:
        name: Strategy identifier
        tickers: List of market tickers to trade
        max_position_per_ticker: Maximum position size per market
        max_total_position: Maximum total position across all markets
        min_signal_confidence: Minimum confidence to act on a signal
        cooldown_seconds: Minimum time between orders
    """

    name: str
    tickers: List[str]
    max_position_per_ticker: int = 100
    max_total_position: int = 500
    min_signal_confidence: float = 0.6
    cooldown_seconds: float = 1.0

    def __post_init__(self) -> None:
        """Validate configuration."""
        if not self.name:
            raise ValueError("Strategy name cannot be empty")
        if not self.tickers:
            raise ValueError("Strategy must have at least one ticker")
        if self.max_position_per_ticker <= 0:
            raise ValueError("max_position_per_ticker must be positive")
        if self.max_total_position <= 0:
            raise ValueError("max_total_position must be positive")
        if not 0 <= self.min_signal_confidence <= 1:
            raise ValueError("min_signal_confidence must be 0-1")
        if self.cooldown_seconds < 0:
            raise ValueError("cooldown_seconds cannot be negative")


@dataclass
class StrategyState:
    """Runtime state tracking for a strategy.

    Attributes:
        is_running: Whether the strategy is currently active
        signals_generated: Total signals generated
        orders_placed: Total orders placed
        fills_received: Total fills received
        errors: Total errors encountered
        started_at: When the strategy was started
        last_signal_at: When the last signal was generated
    """

    is_running: bool = False
    signals_generated: int = 0
    orders_placed: int = 0
    fills_received: int = 0
    errors: int = 0
    started_at: Optional[datetime] = None
    last_signal_at: Optional[datetime] = None


class TradingStrategy(ABC):
    """Abstract base class for all trading strategies.

    Lifecycle:
        1. __init__() - Configure strategy
        2. start() - Begin processing
        3. on_market_update() - Called on each market tick
        4. on_fill() - Called when orders fill
        5. stop() - Graceful shutdown

    Subclasses must implement:
        - evaluate() - Generate signals from market data
        - on_fill() - Handle fill events

    Optional overrides:
        - on_start() - Custom startup logic
        - on_stop() - Custom shutdown logic
        - should_trade() - Additional trade filtering

    Example:
        >>> class MyStrategy(TradingStrategy):
        ...     def evaluate(self, market: MarketState) -> List[Signal]:
        ...         # Generate signals based on market data
        ...         return []
        ...     def on_fill(self, fill: Fill) -> None:
        ...         # Update internal state
        ...         pass
        >>> config = StrategyConfig(name="my_strategy", tickers=["TICKER-A"])
        >>> strategy = MyStrategy(client, config)
        >>> strategy.start()
        >>> strategy.on_market_update(market_state)
        >>> strategy.stop()
    """

    def __init__(
        self,
        client: APIClient,
        config: StrategyConfig,
        risk_manager: Optional[RiskManager] = None,
    ) -> None:
        """Initialize the strategy.

        Args:
            client: API client for market data and order execution
            config: Strategy configuration
            risk_manager: Optional risk manager for trade validation
        """
        self._client = client
        self._config = config
        self._risk_manager = risk_manager
        self._state = StrategyState()
        self._positions: Dict[str, int] = {}
        self._pending_orders: Dict[str, Signal] = {}

    # === Abstract Methods (must implement) ===

    @abstractmethod
    def evaluate(self, market: MarketState) -> List[Signal]:
        """Evaluate market and generate trading signals.

        Called on each market update. Return empty list if no action needed.

        Args:
            market: Current market state

        Returns:
            List of trading signals (may be empty)
        """
        pass

    @abstractmethod
    def on_fill(self, fill: Fill) -> None:
        """Handle a fill event.

        Called when an order is filled. Update internal state as needed.

        Args:
            fill: The fill event
        """
        pass

    # === Lifecycle Methods ===

    def start(self) -> "TradingStrategy":
        """Start the strategy.

        Returns:
            Self for method chaining
        """
        if self._state.is_running:
            return self

        self._state.is_running = True
        self._state.started_at = datetime.now()
        self.on_start()
        return self

    def stop(self) -> None:
        """Stop the strategy gracefully."""
        if not self._state.is_running:
            return

        self.on_stop()
        self._state.is_running = False

    def on_start(self) -> None:
        """Override for custom startup logic.

        Called after strategy is marked as running.
        """
        pass

    def on_stop(self) -> None:
        """Override for custom shutdown logic.

        Called before strategy is marked as stopped.
        """
        pass

    # === Core Loop ===

    def on_market_update(self, market: MarketState) -> List[str]:
        """Process market update and execute trades.

        This is the main entry point called by the trading loop.

        Args:
            market: Current market state

        Returns:
            List of order IDs placed
        """
        if not self._state.is_running:
            return []

        order_ids: List[str] = []

        try:
            # Generate signals
            signals = self.evaluate(market)
            self._state.signals_generated += len(signals)

            if signals:
                self._state.last_signal_at = datetime.now()

            # Process each signal
            for signal in signals:
                # Check confidence threshold
                if signal.confidence < self._config.min_signal_confidence:
                    continue

                # Check if we should trade
                allowed, reason = self.should_trade(signal)
                if not allowed:
                    continue

                # Check cooldown
                if not self._check_cooldown():
                    continue

                # Place order
                try:
                    order_id = self._client.place_order(
                        ticker=signal.ticker,
                        side=signal.side,
                        price=signal.price,
                        size=signal.size,
                    )
                    self._pending_orders[order_id] = signal
                    self._state.orders_placed += 1
                    order_ids.append(order_id)
                except (ValueError, RuntimeError) as e:
                    self._state.errors += 1
                    # Log error but continue processing other signals

        except Exception:
            self._state.errors += 1
            raise

        return order_ids

    def should_trade(self, signal: Signal) -> Tuple[bool, str]:
        """Check if signal should be traded.

        Override for custom filtering logic.

        Args:
            signal: The signal to check

        Returns:
            Tuple of (allowed, reason)
        """
        # Check position limits from config
        current_pos = self.get_position(signal.ticker)

        # Calculate new position after trade
        if signal.side == "BID":
            new_pos = current_pos + signal.size
        else:
            new_pos = current_pos - signal.size

        # Check per-ticker limit
        if abs(new_pos) > self._config.max_position_per_ticker:
            return False, f"Position limit exceeded for {signal.ticker}"

        # Check total position limit
        total_pos = self.get_total_position()
        position_change = abs(new_pos) - abs(current_pos)
        new_total = total_pos + position_change

        if new_total > self._config.max_total_position:
            return False, "Total position limit exceeded"

        # Check with risk manager if available
        if self._risk_manager is not None:
            # Convert BID/ASK to buy/sell for risk manager
            side = "buy" if signal.side == "BID" else "sell"
            allowed, reason = self._risk_manager.can_trade(
                ticker=signal.ticker,
                side=side,
                size=signal.size,
            )
            if not allowed:
                return False, reason

        return True, "Trade allowed"

    def _check_cooldown(self) -> bool:
        """Check if cooldown period has passed.

        Returns:
            True if trading is allowed, False if in cooldown
        """
        if self._state.last_signal_at is None:
            return True

        elapsed = (datetime.now() - self._state.last_signal_at).total_seconds()
        return elapsed >= self._config.cooldown_seconds

    # === Utility Methods ===

    def get_position(self, ticker: str) -> int:
        """Get current position for ticker.

        Args:
            ticker: Market identifier

        Returns:
            Current position size (positive = long, negative = short, 0 = flat)
        """
        return self._positions.get(ticker, 0)

    def get_total_position(self) -> int:
        """Get total absolute position across all tickers.

        Returns:
            Sum of absolute position sizes
        """
        return sum(abs(pos) for pos in self._positions.values())

    def get_state(self) -> StrategyState:
        """Get current strategy state.

        Returns:
            Copy of current StrategyState
        """
        return StrategyState(
            is_running=self._state.is_running,
            signals_generated=self._state.signals_generated,
            orders_placed=self._state.orders_placed,
            fills_received=self._state.fills_received,
            errors=self._state.errors,
            started_at=self._state.started_at,
            last_signal_at=self._state.last_signal_at,
        )

    def get_stats(self) -> Dict[str, Any]:
        """Get strategy statistics.

        Returns:
            Dictionary with strategy statistics
        """
        state = self._state
        return {
            "name": self._config.name,
            "is_running": state.is_running,
            "started_at": state.started_at.isoformat() if state.started_at else None,
            "signals_generated": state.signals_generated,
            "orders_placed": state.orders_placed,
            "fills_received": state.fills_received,
            "errors": state.errors,
            "positions": dict(self._positions),
            "total_position": self.get_total_position(),
            "pending_orders": len(self._pending_orders),
        }

    def _update_position(self, ticker: str, delta: int) -> None:
        """Update position for a ticker.

        Args:
            ticker: Market identifier
            delta: Position change (positive = bought, negative = sold)
        """
        current = self._positions.get(ticker, 0)
        new_pos = current + delta
        if new_pos == 0:
            self._positions.pop(ticker, None)
        else:
            self._positions[ticker] = new_pos
